### ISSUE TITLE
Project immediatly quit on Quest 3

### ISSUE THREAD

**Issue by Nickauhla** [oculus-samples/Unreal-PassthroughSample#6]
Hello,

I've tried to deploy the project on Quest 3, and it immediatly crash on launch.

I am using Unreal 5.3 with Meta XR 1.94.0.
Here's the log when I launch the application.
[odh_logs_2024-03-31 16.56.27.277.txt](https://github.com/oculus-samples/Unreal-PassthroughSample/files/14817006/odh_logs_2024-03-31.16.56.27.277.txt)

I foind it odd to have as many "**Permission denied: process 11313 (uid 10118) doesn't have the required permission: com.oculus.permission.READ_VR_DEVICE_PARAMS**"

Can someone help me please?

**Comment by mderzelle** [comment]
Hi,

Sorry for the wait,

The crash is coming from `Assertion failed: !ScreenTexture.Texture->Desc.IsTextureArray()` which is a known issue.
The issue will be fixed with UE5.4 and future version of the plugin.
Meanwhile, there's 2 workarounds that should work : 
- Make sure "Enable Dynamic Resolution" is disabled in the project settings (Plugins - Meta XR)

or
- Use the Meta fork version of Unreal Engine

**Comment by Nickauhla** [comment]
Thanks for your answer.
Do you have an idea when either the 5.4 version of the meta fork will happen, or the 5.4 compatible version of the metaXR plugin?

**Comment by mderzelle** [comment]
Hi @Nickauhla 
Did the workaround work for you ?

The 5.4 compatible version of the plugin (v67) should be released in July.

**Comment by Nickauhla** [comment]
I've managed to make it work with the fork version of Unreal, yes.
I am now struggling with the scene sharing sample.

I've tried to reach you on Linkedin, without success, would it be possible to have a more direct way to discuss of the samples?

**Comment by mderzelle** [comment]
If you want a more direct way to discuss samples, the Oculus Start Program would be best suited.
https://developer.oculus.com/oculus-start/member/
With this program you have access to a forum and a discord server for more direct interactions.

It is advised to not communicate with external developers through personal networks.

If you don't have an issue with this sample anymore I'd advise closing this thread.

**Comment by mderzelle** [comment]
No update since June 27th, I'm closing this issue.
