### ISSUE TITLE
Niagara Sprite Renderer& Ribbon Renderer Cannot show top on PT Layer 

### ISSUE THREAD

**Issue by HeberRyan** [oculus-samples/Unreal-PassthroughSample#7]
After testing, it was discovered that the Unreal Engine's Niagara Sprite Renderer and Ribbon Renderer cannot show on top the Reconstruction (Underlay) Oculus XR PT Layer. However, mesh render works normally. How can I maintain the Sprite and Ribbon while also showing the Reconstruction Underlay?

**Comment by wangpingsx** [comment]
@HeberRyan  have you tried to change Ribbon Renderer and Sprite Renderer 's Blend Mode to Alpha Blend?

**Comment by HeberRyan** [comment]
> @HeberRyan have you tried to change Ribbon Renderer and Sprite Renderer 's Blend Mode to Alpha Blend?

Thank you for your response, wangpingsx! 
I would like to know how to change the blend mode of the Ribbon Renderer and Sprite Renderer. Could you please give me more specific instructions on where to find and set the blend mode for these renderers? I have been unable to locate the option to do so.
Best
Ryan

**Comment by HeberRyan** [comment]
Accidentally, I found that the blend mode is in the shader. The default sprite renderer material's blend mode is additive. Create a new material and change its blend mode to transparent. Problem solved!
